name: Build And Publish To NPM

on:
  release:
    types: [published]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

jobs:
  build:
    runs-on:
      - linux

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Check build version
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const fs = require("fs")
              const jsonString = fs.readFileSync("package.json")
              const package = JSON.parse(jsonString)
              if (package.version !== "${{ github.ref_name }}") {
                 core.setFailed(`package.json version (${package.version}) not match version of release (${{ github.ref_name }})`) 
              }
            } catch(err) {
              core.setFailed(err)
            }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Enable Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Publish package on NPM
        run: npm publish --access public
