name: Publish To NPM

on:
  release:
    types: [ published ]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

jobs:
  test:
    name: Publish To NPM

    runs-on:
      - self-hosted
      - 8core

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Enable Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish package on NPM
        run: npm publish --access public
